version: '3.8'

services:
  fastapi-service:
    build:
      context: ./fastapi-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - fastapi-service
      - kafka
