services:
  fastapi_service:
    build:
      context: ./fastapi_service
      dockerfile: Dockerfile
    networks:
      - salespulse
    ports:
      - "8000:8000"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - salespulse
    ports:
      - "9092:9092"

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - fastapi_service
      - kafka
    networks:
      - salespulse

networks:
  salespulse:
    driver: bridge
