services:
  fastapi_service:
    build:
      context: ./fastapi_service
      dockerfile: Dockerfile
    networks:
      - salespulse
    ports:
      - "8000:8000"

  kafka:
    image: bitnami/kafka:latest
    environment:
      # KRaft settings for Bitnami image
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - salespulse
    ports:
      - "9092:9092"

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - fastapi_service
      - kafka
    networks:
      - salespulse

networks:
  salespulse:
    driver: bridge
volumes:
  kafka_data:
    driver: local
